spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: usr
    password: pwd
  data:
    mongodb:
      host: localhost
      port: 27017
      username: usr
      password: pwd
      database: library
      authentication-database: admin
  main:
    allow-circular-references: true