spring:
  mongodb:
    embedded:
      version: 4.4.11
  data:
    mongodb:
      port: 8081
      database: library

mongock:
  change-logs-scan-package:
    - ru.otus.spring.hw12.mongock.changelog

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG